# Print a new line at the start of the prompt
add_newline = true

# Make prompt a two lines instead of single line
[line_break]
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
 [character]
 success_symbol = "[âœ](bold green) "
 error_symbol = "[âœ—](bold red) "
 vicmd_symbol = "[V](bold green) "

# Use custom format
 format = """

 [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
 [â”‚](bold green)$directory$rust$package
 [â””â”€>](bold green) """

[battery]
full_symbol = " ğŸ”‹"
charging_symbol = " âš¡ï¸"
discharging_symbol = " ğŸ’€"

[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style and ğŸ’€ symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[[battery.display]]  # "bold yellow" style and ğŸ”‹ symbol when capacity is between 30% and 100%
threshold = 100
style = "bold green"


[username]
style_user = "white italic bold"
style_root = "black italic bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "on [$hostname](bold italic blue) "
trim_at = ".companyname.com"
disabled = false

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[time]
disabled = false
format = ' ğŸ•™[\[ $time \]]($style) '
time_format = "%r"
utc_time_offset = "local"
use_12hr = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
